anchor:
  [1, 2, 3]
model:
  backbone:
  - Conv: 
      args: {out_channels: 32, kernel_size: 3}
  - Conv: 
      args: {out_channels: 64, kernel_size: 3, stride: 2}
  - Conv: 
      args: {out_channels: 64, kernel_size: 3}
  - Conv: 
      args: {out_channels: 128, kernel_size: 3, stride: 2}
  - Conv: 
      args: {out_channels: 64, kernel_size: 1}
  - Conv: 
      args: {out_channels: 64, kernel_size: 1}
      source: -2
  - Conv: 
      args: {out_channels: 64, kernel_size: 3}
  - Conv: 
      args: {out_channels: 64, kernel_size: 3}
  - Conv: 
      args: {out_channels: 64, kernel_size: 3}
  - Conv: 
      args: {out_channels: 64, kernel_size: 3}
  - Concat: 
      source: [-1, -3, -5, -6]
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
  - MP: 
      args: []
  - Conv: 
      args: {out_channels: 128, kernel_size: 1}
  - Conv: 
      args: {out_channels: 128, kernel_size: 1}
      source: -3
  - Conv: 
      args: {out_channels: 128, kernel_size: 3, stride: 2}
  - Concat: 
      source: [-1, -3]
  - Conv: 
      args: {out_channels: 128, kernel_size: 1}
  - Conv: 
      args: {out_channels: 128, kernel_size: 1}
      source: -2
  - Conv: 
      args: {out_channels: 128, kernel_size: 3}
  - Conv: 
      args: {out_channels: 128, kernel_size: 3}
  - Conv: 
      args: {out_channels: 128, kernel_size: 3}
  - Conv: 
      args: {out_channels: 128, kernel_size: 3}
  - Concat: 
      source: [-1, -3, -5, -6]
      tags: 8x
  - Conv: 
      args: {out_channels: 512, kernel_size: 1}
  - MP: 
      args: []
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
      source: -3
  - Conv: 
      args: {out_channels: 256, kernel_size: 3, stride: 2}
  - Concat: 
      source: [-1, -3]
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
      source: -2
  - Conv: 
      args: {out_channels: 256, kernel_size: 3}
  - Conv: 
      args: {out_channels: 256, kernel_size: 3}
  - Conv: 
      args: {out_channels: 256, kernel_size: 3}
  - Conv: 
      args: {out_channels: 256, kernel_size: 3}
  - Concat: 
      source: [-1, -3, -5, -6]
  - Conv: 
      args: {out_channels: 1024, kernel_size: 1}
      tags: 16x
  - MP: 
      args: []
  - Conv: 
      args: {out_channels: 512, kernel_size: 1}
  - Conv: 
      args: {out_channels: 512, kernel_size: 1}
      source: -3
  - Conv: 
      args: {out_channels: 512, kernel_size: 3, stride: 2}
  - Concat: 
      source: [-1, -3]
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
      source: -2
  - Conv: 
      args: {out_channels: 256, kernel_size: 3}
  - Conv: 
      args: {out_channels: 256, kernel_size: 3}
  - Conv: 
      args: {out_channels: 256, kernel_size: 3}
  - Conv: 
      args: {out_channels: 256, kernel_size: 3}
  - Concat: 
      source: [-1, -3, -5, -6]
  - Conv: 
      args: {out_channels: 1024, kernel_size: 1}
      tags: 32x
  head:
  - SPPCSPC: 
      args: [512]
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
  - Upsample: 
      args: [None, 2, nearest]
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
      source: 16x
  - Concat: 
      source: [-1, -2]
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
      source: -2
  - Conv: 
      args: {out_channels: 128, kernel_size: 3}
  - Conv: 
      args: {out_channels: 128, kernel_size: 3}
  - Conv: 
      args: {out_channels: 128, kernel_size: 3}
  - Conv: 
      args: {out_channels: 128, kernel_size: 3}
  - Concat: 
      source: [-1, -2, -3, -4, -5, -6]
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
  - Conv: 
      args: {out_channels: 128, kernel_size: 1}
  - Upsample: 
      args: [None, 2, nearest]
  - Conv: 
      args: {out_channels: 128, kernel_size: 1}
      source: 8x
  - Concat: 
      source: [-1, -2]
  - Conv: 
      args: {out_channels: 128, kernel_size: 1}
  - Conv: 
      args: {out_channels: 128, kernel_size: 1}
      source: -2
  - Conv: 
      args: {out_channels: 64, kernel_size: 3}
  - Conv: 
      args: {out_channels: 64, kernel_size: 3}
  - Conv: 
      args: {out_channels: 64, kernel_size: 3}
  - Conv: 
      args: {out_channels: 64, kernel_size: 3}
  - Concat: 
      source: [-1, -2, -3, -4, -5, -6]
  - Conv: 
      args: {out_channels: 128, kernel_size: 1}
  - MP: 
      args: []
  - Conv: 
      args: {out_channels: 128, kernel_size: 1}
  - Conv: 
      args: {out_channels: 128, kernel_size: 1}
      source: -3
  - Conv: 
      args: {out_channels: 128, kernel_size: 3, stride: 2}
  - Concat: 
      source: [-1, -3, 63]
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
      source: -2
  - Conv: 
      args: {out_channels: 128, kernel_size: 3}
  - Conv: 
      args: {out_channels: 128, kernel_size: 3}
  - Conv: 
      args: {out_channels: 128, kernel_size: 3}
  - Conv: 
      args: {out_channels: 128, kernel_size: 3}
  - Concat: 
      source: [-1, -2, -3, -4, -5, -6]
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
  - MP: 
      args: []
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
      source: -3
  - Conv: 
      args: {out_channels: 256, kernel_size: 3, stride: 2}
  - Concat: 
      source: [-1, -3, 51]
  - Conv: 
      args: {out_channels: 512, kernel_size: 1}
  - Conv: 
      args: {out_channels: 512, kernel_size: 1}
      source: -2
  - Conv: 
      args: {out_channels: 256, kernel_size: 3}
  - Conv: 
      args: {out_channels: 256, kernel_size: 3}
  - Conv: 
      args: {out_channels: 256, kernel_size: 3}
  - Conv: 
      args: {out_channels: 256, kernel_size: 3}
  - Concat: 
      source: [-1, -2, -3, -4, -5, -6]
  - Conv: 
      args: {out_channels: 512, kernel_size: 1}
  - RepConv: 
      args: [256, 3, 1]
      source: 75
  - RepConv: 
      args: [512, 3, 1]
      source: 88
  - RepConv: 
      args: [1024, 3, 1]
      source: 101
  - IDetect: 
      args: [nc, anchors]
      source: [102, 103, 104]
