general:
  out_path: runs
  task: train
  deivce: [0]
  cpu_num: 16
  use_wandb: False
  lucky_number: 10
  exist_ok: True
  resume_train: False
  use_TensorBoard: False
data:
  batch_size: 16 
  class_num: 80
  image_size: [640, 640]
  shuffle: True
  pin_memory: True
train:
  epoch: 500
  optimizer:
    type: SGD
    args:
      lr: 0.01
      weight_decay: 0.0005
      momentum: 0.937
  loss:
    objective:
      BCELoss: 0.5
      BoxLoss: 7.5  
      DFLoss: 1.5
    aux:
      0.25
    matcher:
      iou: CIoU
      topk: 10
      factor:
        iou: 6.0
        cls: 0.5
  scheduler:
    type: LinearLR
    warmup:
      epochs: 3.0
    args:
      total_iters: ${hyper.train.epoch}
      start_factor: 1
      end_factor: 0.01
  ema:
      enabled: true
      decay: 0.995
