path: tests/data
train: train
validation: val

auto_download:
  images:
    base_url: https://github.com/WongKinYiu/yolov9mit/releases/download/v1.0-alpha/
    train:
      file_name: mock_train
      file_num: 5
    val:
      file_name: mock_val
      file_num: 5
  annotations:
    base_url: https://github.com/WongKinYiu/yolov9mit/releases/download/v1.0-alpha/
    annotations:
      file_name: mock_annotations
